Fit image options
hkalexling/Mango pull request #317
Opened 2022-07-05 21:22 UTC by Hiers

Adding the image fit feature mentioned in #147.

The setFit function is hardcoded to look for the css file and attribute on those exact spots and looks likely to break if that file is changed. Asides from this, the only other way I know is to make a function to look for it given the name of the file and attribute, but it'd be a function that would only be used on this one occasion.

And if anyone has a better idea for how the option should appear in the settings I'd like to hear it, design is not my passion.

2022-07-05 21:40 UTC, Hiers commented
Note: the real size option has the added benefit of having the browser's native scaling work as expected.

2022-07-07 08:30 UTC, Leeingnyo commented
Thank you for PR!

> The setFit function is hardcoded to look for the css file and attribute on those exact spots and looks likely to break if that file is changed. Asides from this, the only other way I know is to make a function to look for it given the name of the file and attribute, but it'd be a function that would only be used on this one occasion.

We would write styles to classes (such as `.vertical`, `.horizontal`, `.original`), and in JS, adding classes to tags or removing classes from tags according to option value. I saw just codes and didn't see actual implementation on a browser yet. I'll tell you what would be a detailed way (which tags to have classes, what contents that class style would have) after seeing this on a browser.

2022-07-08 08:42 UTC, hkalexling commented
Thanks! Yeah agreed with @Leeingnyo I think accessing the styles directly is a bit too hacky. I took a quick look and I think in the `setFit` function we can simply do `this.fitType = fitType` without touching the styles? The `img` style will be updated in `src/views/reader.html.ecr`.

2022-07-12 01:28 UTC, Leeingnyo commented
@Hiers Sorry to late!

I misunderstood something. please forget about what i said before.

It seemed you used the hardcoded style to remove this following rule

```
canvas,
img,
video {
  /* 1 */
  max-width: 100%;
  /* 2 */
  height: auto;
  /* 3 */
  box-sizing: border-box;
}
```

Rather than removing to use `document.styleSheets[0].rules[21].style.maxWidth` directly, We could override a css rule like this

```html
<uk-img
  style="
    max-width:${fitType === 'horz' ? '100%' : 'none'}; /* <-- use 'none' instead of '' */
    max-height:${fitType === 'vert' ? '100%' : 'none'};
  "
/>
```

an inline style rule would override the rule of `mango.css` and we should apply `'none'` to cancel `max-width` and `max-height`

2022-07-12 01:54 UTC, Leeingnyo commented
As shown in this picture, the position of a right flip panel isn't on expected position in real mode

<img width="510" alt="스크린샷 2022-07-12 오전 10 13 42" src="https://user-images.githubusercontent.com/6760150/178388289-c02438d1-0e14-4516-930b-3545585b36c8.png">

it would be fixed giving `width: fit-content;` to the wrapper div (parent of `uk-img`).

2022-07-12 02:02 UTC, Leeingnyo requested changes

2022-07-12 02:06 UTC, Leeingnyo commented on public/js/reader.js
> +						this.fitType = savedFitType;
If you don't mind, please fix to `if (savedFitType) {` 😃

2022-07-12 02:35 UTC, Leeingnyo requested changes

2022-07-12 02:35 UTC, Leeingnyo commented on src/views/reader.html.ecr
> +        <div x-cloak x-show="!loading && mode !== 'continuous'" class="uk-flex uk-flex-middle" style="height:${fitType === 'vert' ? '100vh' : ''">
to use JS expression in attribute, add colon in front of attribute name

```
:style="`${fitType === 'vert' ? 'height:100vh' : ''}`"
```

2022-07-13 08:37 UTC, Hiers commented
Ah, I didn't realise my problem was deleting `max-width` instead of setting it to `none`, thank you.

Your edit made me realise I never explicitly said it, but I was making the fit image feature to be for paged mode only, which is what made sense to me. Do you think this should be available in continuous mode too?

2022-07-15 13:30 UTC, Leeingnyo approved these changes

2022-07-16 03:44 UTC, hkalexling commented
Thanks both! I noticed another small issue - the page flip panels are still not positioned correctly. See screenshot below.

![DeepinScreenshot_select-area_20220716113915](https://user-images.githubusercontent.com/7845831/179337697-d8690d05-9013-4412-b35c-47a60f352302.png)

The right panel should be the right most 1/3 area of the entire screen, and not the right 1/3 of the page. I believe this is caused by the new `position: relative` style in the parent of `uk-img`. It looks like it can be fixed by moving `position: relative` to the `uk-section` tag instead, since it always has 100% width. Do you mind giving it a try? But let me know if I am missing anything!

2022-07-16 11:02 UTC, Hiers commented
Nice catch! And your fix did work.

2022-07-17 03:55 UTC, merged

2022-07-17 03:55 UTC, hkalexling commented
LGTM, thanks!